aviator-co/av

cmd/av/main.go, cmd/av/stack.go, internal/git/git.go, internal/git/utils.go, internal/stacks/stacks.go, internal/utils/cleanup/cleanup.go, internal/utils/cleanup/cleanup_test.go
```
$ go run ./cmd/av -C ~/Aviator/mergequeue-demo/ stack branch foobar      
Created branch foobar
$ go run ./cmd/av -C ~/Aviator/mergequeue-demo/ stack branch foobar      
error: cannot create branch foobar (does it already exist?)
```
=> [MER-671] Implement basic av stack branch command

cmd/av/pr.go
Turns out the old way of doing it only works if the branch already exists on the upstream (I think).
=> [MER-833] Fix "failed to set upstream" in av pr create

.goreleaser.yaml, cmd/av/main.go, go.mod, go.sum, internal/config/config.go, internal/config/version.go
=> [MER-848] Add automatic version check

cmd/av/stack_tree.go
=> [MER-873] Highlight current branch in the stack

cmd/av/stack_branch.go, internal/git/git.go
not totally sure what i'm doing but i think it works??
=> [MER-877] cli: improve error message if stack branch fails

cmd/av/stack_next.go, cmd/av/stack_prev.go
Filled out stubbed commands `stack next` and `stack prev`
Fiddle around with commands and `stack branch` and see them successfully updating another repo's checked out branch
=> [MER-1006] added stack prev and next commands

cmd/av/stack_next.go, cmd/av/stack_prev.go
=> Fixed newlines on returns

internal/config/config.go
=> feat: Add support for GITHUB_TOKEN env var

e2e_tests/stack_sync_amend_test.go, internal/actions/pr.go, internal/editor/editor.go, internal/editor/editor_test.go, internal/git/gittest/commit.go, internal/git/show.go, internal/utils/stringutils/subject.go, internal/utils/stringutils/subject_test.go, internal/utils/templateutils/templateutils.go
This PR was created with the code contained within this PR 👀.
=> feat: Open editor to specify PR title/body

cmd/av/commit.go, cmd/av/commit_split.go, cmd/av/main.go, internal/git/git.go
=> feat: Add commit split command

internal/actions/pr.go
When a branch parent is trunk, use the remote tracking branch instead of
using the locally checked out trunk branch. This makes more accurate
commit list, and in case where the user intentionally removes local
trunk branch to avoid unintentional commit on master/main, av pr create
starts working.
=> feat: Use the remote tracking branch for finding commits

e2e_tests/stack_sync_test.go, internal/actions/sync_branch.go
When a conflict happens, in some cases the parent is updated before
conflict is resolved. When sync is aborted, the parent is already moved,
so it won't get back to the original state. The parent update should be
done after --continue.
Also, the parent should be updated even if it's not trunk. It should
update the parent hash as well.
This change creates a sync continuation for all cases. The continuation
contains the data needed for updating parents. The continuation is
called inline when there's no conflict. If there's a conflict, the
continuation is saved and applied later.
=> fix: Update the parent consistently

internal/git/git.go
Currently if there's no remote "origin", it shows "error: git remote:
exit status 2". This change shows "this repository doesn't have a remote
origin".
=> feat: Show friendly error message when there is no remote

docs/README.md, docs/av.1.md, docs/convert-manpages.go, go.mod, go.sum
This doesn't cover subcommands, but acts as the basis of the manpages.
Part of #124.
=> feat: Add the first manual page

cmd/av/commit.go, cmd/av/commit_create.go, cmd/av/main.go, cmd/av/stack_branchcommit.go, cmd/av/stack_sync.go, internal/actions/errors.go, internal/actions/sync_stack.go
- need to/ will add more flags on top of this pr, but this is the scaffolding for the commit create cmd
=> feat: Adding av commit create

cmd/av/stack_sync.go, e2e_tests/stack_sync_delete_merged_test.go, internal/actions/sync_stack.go, internal/git/git.go
=> feat: Add an option to delete merged branches

cmd/av/commit_create.go
=> fix: Fix failed git checkout after av stack sync on av commit create

docs/av-commit-create.1.md, docs/av.1.md
=> feat: Add av commit create man page

internal/actions/sync_branch.go
Per title.
```
$ av stack sync
Synchronizing branch 2023-05-30-one...
- fetching latest pull request information for 2023-05-30-one
- skipping sync for merged branch (merged in commit 87232f0)
Synchronizing branch 2023-05-30-two...
- fetching latest pull request information for 2023-05-30-two
- rebased without conflicts
- this branch is now a stack root based on trunk branch main
- pushing 2023-05-30-two... okay
```
=> fix(stack sync): Fetch merge commits from remote before rebasing children

docs/av-commit-amend.1.md, docs/av-commit-create.1.md
Try to align with the Git man pages as much as possible.
=> doc: Update the style

docs/av-commit-split.1.md, docs/av-init.1.md
=> doc: Add more manual pages

cmd/av/stack_sync.go, docs/av-stack-sync.1.md
=> doc: [MER-2383] Add manpage for av stack sync

cmd/av/pr.go, cmd/av/pr_create.go
Working hard to find every way to break things.
=> refac: [MER-2427] Add pr.go.

cmd/av/stack_reorder.go
Tested manually with a local repo. This won't restore the branch state, but
aborts the in-progress cherry-pick.
=> [MER-2497] Abort git-cherry-pick on --abort

docs/av-stack-reorder.1.md
This is a bare minimum. We can add more explaination later.
=> [MER-2335] Add a manpage for av stack reorder

internal/actions/pr.go
I noticed this behavior:
* Create a PR using `av`
* Merge the PR
* Forget to switch branches, add a new commit to the branch that was merged
* Run `av pr create`
* `av` doesn't complain, it just pushes to the branch and edits the PR metadata
This also fixes the use of `--force`; before, it wasn't actually doing anything.
=> fix: Don't re-use closed/merged PRs

.github/dependabot.yml
=> [MER-3739] Configure dependabot to update libraries

internal/actions/pr.go
Hi, I tried to fix https://github.com/aviator-co/av/issues/236
Please review my change. Thank you
=> Update error message

cmd/av/stack_tree.go
=> Make stack tree nicer

cmd/av/stack_submit.go
Addressed https://github.com/aviator-co/av/issues/253
=> Add `--current` option to stack submit command

cmd/av/stack.go, cmd/av/stack_orphan.go, e2e_tests/stack_orphan_test.go
Issue: https://github.com/aviator-co/av/issues/243
I tried to implement `av stack orphan` command.
=> Implement av stack orphan command

internal/utils/browser/browser.go
=> Support WAYLAND_DISPLAY environment variable

cmd/av/stack.go, cmd/av/stack_adopt.go, cmd/av/stack_restack.go, docs/av-stack-adopt.1.md, docs/av-stack-restack.1.md, e2e_tests/stack_restack_test.go, go.mod, go.sum, internal/git/state_file.go, internal/treedetector/detector.go, internal/treedetector/util.go, internal/utils/sliceutils/append.go, internal/utils/stackutils/stackutils.go
=> Add av stack adopt command

cmd/av/stack_switch.go
=> Fall back to the first branch in the list if the current branch is not in the switch list

cmd/av/stack_next.go
=> Show help text for the selection prompt

.github/workflows/release.yml
=> Set GITHUB_TOKEN

.github/workflows/go.yml
=> Add concurrency control to the Go test workflow

cmd/av/auth.go, cmd/av/commit.go, cmd/av/pr.go, cmd/av/stack.go, cmd/av/version.go
=> Update the command descriptions to be capitalized

cmd/av/commit_common.go, cmd/av/stack_adopt.go, cmd/av/stack_next.go, cmd/av/stack_reparent.go, cmd/av/stack_restack.go, cmd/av/stack_switch.go, cmd/av/stack_sync.go, internal/utils/uiutils/tea.go
=> Consolidate the Bubbletea program start code

cmd/av/stack_branch.go
=> Use a resolved commit hash as the starting point for the new branch

internal/gh/ghui/push.go
addressed https://github.com/aviator-co/av/issues/396
=> Check local metadata is updated compared with PR's metadata

.pre-commit-config.yaml
=> Prevent accidentally committing to master

cmd/av/stack_adopt.go, cmd/av/stack_switch.go, internal/utils/uiutils/prompt.go
=> Support ctrl+n and ctrl+p for moving up and down in the prompt

cmd/av/main.go
Fixes https://github.com/aviator-co/av/issues/424
=> Skip update check on av completion

cmd/av/stack_submit.go
Small PR adding the ability to open draft PRs when doing submit .
Closes #422
=> feat: `av stack submit --draft` add the ability to open PRs as draft

.github/workflows/release.yml, .goreleaser.yaml
=> Push linux packages to fury.io

internal/gh/ghui/push.go
We should have skipped the push if the local and remote PR metadata are
the same.
https://github.com/aviator-co/av/issues/483
=> Fix the condition flip in GitHubPushModel.calculateChangedBranches

.goreleaser.yaml
=> update goreleaser.yaml, field renamed in v2.2

.github/workflows/go.yml, .github/workflows/pre-commit.yml
=> Fix pre-commit changes

cmd/av/sync.go
=> Run pre-av-sync hook before running the sync command

cmd/av/sync.go
This has been here for a long time. We should be able to drop this.
=> Remove av-sync's behavior change warning

cmd/av/pr.go
=> Run hooks on `av pr` command
