- go.mod
- internal/git/const.go
- internal/git/git.go
- internal/git/git_test.go
- internal/git/listrefs.go
- internal/git/listrefs_test.go
- internal/stacks/stacks.go
This is preparation for being able to run `av pr` -- we want to be able to figure out what refs already have remote tracking information.
Also added a test case! Yay!
> [MER-670] Implement git.Repo.ListRefs

- cmd/av/helpers.go
- cmd/av/init.go
- cmd/av/pr.go
- internal/actions/pr.go
- internal/git/show.go
- internal/meta/repository.go
This also moves a lot of the code that was in `./cmd/av/pr.go` into a new folder:
`./internal/actions`. The reason for this is to be able to extract out certain
things that we'll need to do in multiple contexts (in this case, I want to be
able to implement an `av stack submit` command, which will involve opening a PR
for every branch in the stack).
That code is mostly unchanged, except for the bit where we now read the subject
and body from the commit in order to populate the PR title/body. I'm going to
submit this PR using this strategy, so... wish me luck! 🤞
> [MER-867] Add default PR title from commit subject

- cmd/av/stack.go
- cmd/av/stack_reparent.go
- cmd/av/stack_sync.go
- e2e_tests/av.go
- e2e_tests/stack_reparent_test.go
- go.mod
- go.sum
- internal/git/gittest/repo.go
- internal/meta/branch.go
- internal/utils/sliceutils/sliceutils.go
I originally wanted to do `av stack sync --parent <newparent>`, but it was different enough from a sync that I made it its own command. I'm still not 100% set on that but... 🤷.
Also, it's possible for there to be a rebase conflict during this. It's possible to get into an undesirable state if you then abort that rebase (because av thinks the parent is `<newparent>` but the git branch is still based on `<oldparent>`).
Nonetheless, I think I'd like to merge this as is and think about that limitation a bit later.
> Implement av stack reparent command

- .goreleaser.yaml
- cmd/av/main.go
As seen from two different terminals (Hyper with solarized theme and then from JetBrains built in terminal):
> [MER-871] Improve upgrade message formatting, fix v prefix issue in released version

- cmd/av/pr.go
- internal/actions/pr.go
- internal/config/config.go
Created this PR as a draft with
```
av pr create --draft
```
Also, since we haven't released #36 I thought it made sense to put all of that kind of thing underneath a `pullRequests` config section.
> Add ability to create draft PRs with av pr create

- internal/actions/pr.go
- internal/gh/client.go
- internal/gh/common.go
- internal/gh/pullrequest.go
This allows users to open PR's outside of `av` and then let av know about
the state of that PR. This is mostly useful in scenarios where users open
the first (root) PR using the GH UI, then realize that they want to stack
their work on top if it. Before this commit, that wasn't possible (without
closing the original PR and then re-creating it with `av pr create`).
When we implement `av stack submit`, this should also happen automatically
(for every PR in the stack), but that's a bridge we haven't quite reached.
> Fetch PR info from GH before trying to open it

- cmd/av/stack_next.go
- cmd/av/stack_prev.go
added `--first` and `--last` shortcuts to `av stack prev` and `av stack next` respectively.
Tested locally creating a stack of branches `blah1`, `blah2`, and finally `blah3` and then ran the following commands to show things working:
> feat(stacks): added shortcut flag to stack prev and stack next

- cmd/av/stack_sync.go
- internal/actions/push.go
- internal/git/err.go
- internal/utils/colors/colorutils.go
Also optimizes no not push during `av stack sync` if the remote tracking branch is already up to date. Ideally, this wouldn't be necessary, but `git push` is a bit slow even if theres nothing to do.
> fix: Don't push branch if PR hasn't been created yet

- cmd/av/pr.go
- cmd/av/stack.go
- cmd/av/stack_next.go
- cmd/av/stack_prev.go
- cmd/av/stack_submit.go
- cmd/av/stack_sync.go
- internal/actions/pr.go
- internal/gh/pullrequest.go
- internal/meta/branch.go
`av stack submit` command was added that pushed the current state of the stack - i.e. creates PRs for every branch that doesn't have them and fixes the base branch of the PRs that already exist to be the correct one.
This covers work for both MER-1024 and MER-1007
- created fresh stack locally and ran the command correctly seeing the full stack get submitted
- created fresh stack - create one PR and set the base ref branch to the wrong thing - correctly see the stack submitted and the one wrong base branch get updated.
Initial PR created for branch `submit3` onto `main` as normal:
`av stack submit` command called and the three PRs are submitted and in the case of `submit3` corrected:
> feat(stacks): add av stack submit command

- cmd/av/fetch.go
- cmd/av/init.go
- cmd/av/main.go
- cmd/av/pr.go
- cmd/av/stack_submit.go
- cmd/av/stack_sync.go
- internal/actions/pr.go
- internal/actions/push.go
- internal/actions/reparent.go
- internal/gh/client.go
- internal/gh/pullrequest.go
- internal/git/git.go
- internal/meta/branch.go
- when a stack is partially merged, a stack sync call will now `auto-rebase` onto the trunk commit `tc`
- if `tc` is the HEAD of trunk, then we simply reparent to trunk
- if `tc` is not the HEAD of trunk, then we create a new branch with its HEAD at `tc` and reparent to that branch so that stacks continue to work as normal
- added new client pull request functions that access the commit `oid` for both the standard `MERGE` case, as well as the `FAST FORWARD` case.
- added new `GetClient` function that lazy inits the GitHub client with `sync.Once` - switched all functions to use this method but left the old `NewClient` method present if we need it for some reason.
Ran the following as a test:
- locally created a stack with three branches stacked on each other: <img width="852" alt="Screen …
> feat(stack sync): auto rebase branches after merge

- internal/actions/pr.go
- internal/actions/pr_test.go
- internal/meta/branch.go
I think this will help us be more robust against weird things happen because we're trying to figure out the users intention based on how the PRs are arranged on GitHub.
This also will mean that we don't have to use the `avbeta-stackedprs` label since we can just read the metadata from the PR comment. I think this will be necessary to avoid accidentally injecting stacked PRs functionality into existing dev workflows.
This is what it looks like:
> feat: Add stack metadata to PR on creation

- internal/actions/pr.go
- internal/actions/pr_test.go
- internal/gh/pullrequest.go
This PR adds `parentPull` to stack metadata. It also will update the metadata whenever `CreatePullRequest` is called (_i.e._, when doing `av pr create` or `av stack submit`).
We'll probably need to detect if things are bad™ on the server side of things and recommend running `av stack submit`, but at least this should make it so that the logic for constructing stacks is more explicit and intentional and consistent and less likely to do unexpected things.
> feat: Include parent pull in stack metadata, update metadata on stack submit

- internal/actions/sync_branch.go
- internal/config/config.go
- internal/gh/pullrequest.go
- internal/utils/ghutils/ghutils.go
I don't like the diverging-convering logic of this where we have the `syncBranchUpdateNewTrunk` being called from `syncBranchRebase` **and** `syncBranchContinue`. Might try to think about how to do it better in the future, but this is probably fine for now.
> fix: Update base branch during av stack sync

- cmd/av/stack_sync.go
- e2e_tests/stack_sync_test.go
This fixes how we store the list of branches being synced during the current `av stack sync`. This bug would only manifest if the stack sync was being run from a branch that is not at the end of the stack and the stack sync was interrupted on a branch that comes after the originally checked out branch in the stack.
Confirmed that the new test failed with the code changes and passes now.
> fix: Construct correct list of branches to be synced during stack sync

- e2e_tests/stack_sync_merge_commit_test.go
- internal/actions/sync_branch.go
- internal/meta/branch.go
> fix: Stack sync rebase properly after parent is merged

- cmd/av/stack_sync.go
- internal/actions/sync_branch.go
> fix: Don't try to change the base branch of closed PRs

- internal/actions/pr.go
We've been using the embedded metadata in the PR description for a few months on the server side now, so there's no need to add the `avbeta-stackedprs` label anymore.
> feat: Stop applying avbeta-stackedprs label

- cmd/av/stack_sync.go
- internal/actions/sync_branch.go
Fixing this as reported by a customer.
Before this, we would actually un-draft (aka _mark ready for review_) PRs that were in a draft state if we were re-parenting the PR.
Incidentally, while fixing that bug, I realized that we actually were never transitioning PR's to a draft state at all when they should have been.
With this PR, I verified that now:
* PRs that should be switched to draft during re-parent (to avoid adding unnecessary codeowners) actually are
* PRs that are in a draft state when the re-parent runs continue to stay draft PRs
> fix: Don't un-draft PRs during re-parent

- internal/actions/pr.go
> fix: Use `git push --force-with-lease` in `av pr create`

- go.mod
- go.sum
- internal/editor/editor.go
- internal/editor/editor_test.go
Fixing a bug reported by a customer.
Now we parse the result of `EDITOR`/`GIT_EDITOR` with shell syntax.
This is what [GitHub's `hub` CLI does](https://github.com/github/hub/issues/721) as well as what Git itself does:
```
$ git help var
...
GIT_EDITOR
Text editor for use by Git commands. The value is meant to be interpreted by the shell when it is used. Examples: ~/bin/vi, $SOME_ENVIRONMENT_VARIABLE,
"C:\Program Files\Vim\gvim.exe" --nofork. The order of preference is the $GIT_EDITOR environment variable, then core.editor configuration, then $VISUAL,
then $EDITOR, and then the default chosen at compile time, which is usually vi.
...
```
This PR adds some tests and I'm actually submitting the PR with `EDITOR="code --wait" av pr create --draft`. Notably, it doesn't support the …
> fix: Parse EDITOR with shell syntax

- cmd/av/stack.go
- cmd/av/stack_branchcommit.go
- internal/git/git.go
This change adds a new command `av stack branch-commit`. This creates a
branch and a commit in one shot. The branch name can be auto-generated
if unspecified.
The command name is long, but the user can create a git-alias for
shorthand. For example:
```
[alias]
bc = !av stack branch-commit
```
This allows the user to run `git bc -a -m "Add a new feature"`, which
ends up calling av-cli.
> feat: Add stack branch-commit command

- internal/actions/sync_branch.go
If a PR is based on "main", it should be rebased on top of
"origin/main", not local "main" branch.
> fix: Use the remote tracking branch for the sync

- internal/actions/pr.go
- internal/git/show.go
Currently we show the commit message subjects (the first line of the
message) as the comment in the PR message editor. This shows the message
body as well. This is useful when there are multiple commits or when
there is a PR template (.github/PULL_REQUEST_TEMPLATE.md) exists.
> feat: Show the commit message body

- cmd/av/stack.go
- cmd/av/stack_tidy.go
This command is used to update the av-cli's internal branch metadata
based on the Git branches to some extent. The expected usage is that
after a branch is merged or deleted, run this command to synchronize the
internal metadata.
Probably we can do more magic and hide the details on the branch
metadata furthermore, and automatically tidies up in av stack sync. That
can be done in the future. Right now, unable to delete a branch is
critical, and this should act as a stop-gap solution.
> feat: Add av stack tidy

- internal/actions/pr.go
The comment prefix doesn't have to have a space. This should trim the
comments properly when a comment line doesn't contain anything but '%%'.
> fix: trim the comments properly

- cmd/av/stack_tree.go
- internal/git/git.go
> feat: Support detached HEAD in stack tree

- internal/actions/pr.go
- internal/actions/push.go
- internal/actions/sync_branch.go
Each local git branch can have an optional upstream branch. While the
name looks like the push destination of the branch, it's not. Unless
user specifically configure so, `git push` pushes a branch to the same
name branch on the remote (the simple strategy as described in `man 1
git-push`). This explains the behavior in the TODO comment in
internal/actions/pr.go "I think currently things will break if the
upstream name is not the same name as the local", because git's default
strategy is pushing to the same branch, not to the upstream branch.
The upstream branch is rather used when doing `git rebase`. Without an
argument, it rebases to the upstream branch. Likewise, when `git pull`
does the rebase, it'll rebase to the upstream branch. In many cases, if
a PR is rebased, the intention would …
> fix: Do not use set-upstream

- cmd/av/branchmeta.go
- cmd/av/main.go
- internal/meta/branch.go
This adds hidden branch-meta commands for the internal metadata access.
Useful for debugging / addressing user issues.
This neglects the parent-child relationship maintenance and just try to
rebuild the relationship from parents for all branches.
> feat: Add hidden branch-meta commands

- cmd/av/pr.go
- internal/actions/pr.go
Previously, if there's an existing PR, an editor pops open, but the
content is discarded anyway. Now it won't opens an editor in such case.
With the new flag `--edit`, an editor opens for an existing PR. The
content is pre-filled with the existing PR description and updated
contents are reflected to the PR.
> feat: allow editing a PR description

- cmd/av/stack_sync.go
- internal/actions/reparent.go
- internal/actions/sync_branch.go
- internal/git/rebase.go
> feat: Add --skip option to av stack sync

- internal/meta/branch.go
For consistency, serialize `pullRequest.state` rather than `pullRequest.State`.
This isn't backwards incompatible because when JSON is unmarshalled, it's unmarshaled in a case insensitive way.
> fix: Correct case of JSON meta serialization

- e2e_tests/stack_sync_trunk_test.go
- internal/actions/sync_branch.go
- internal/git/gittest/repo.go
Without this fix, the test fails.
> fix: Fix --trunk so that it actually rebases to the upstream trunk

- internal/actions/pr.go
> fix: Set the parent when creating a PR

- e2e_tests/helpers.go
- e2e_tests/stack_sync_test.go
- internal/actions/sync_branch.go
> fix: Update recorded parent's HEAD after rebase

- e2e_tests/stack_sync_merge_commit_test.go
- internal/actions/sync_branch.go
I think this bug was introduced in #103. I see how it happened and it suggests to me that the code is a little bit hard to follow at the moment. There's room to clean it up so that bugs like this don't reoccur. I don't think the version of `av` with this bug present has been released.
The test I added fails without this change (and I noticed this issue locally).
> fix: Fix av CLI not re-parenting children

- cmd/av/stack_branchcommit.go
- internal/git/branch.go
Deletes a branch during `av stack branch-commit` if the commit fails (e.g., due to pre-commit hooks).
Also a few minor things like language tweaks and adding `av stack bc` as an alias.
Fixes #102.
> fix: Cleanup on failure for av stack branch-commit

- e2e_tests/stack_reparent_test.go
- internal/actions/reparent.go
> feat: Use remote tracking branch if it's trunk

- e2e_tests/stack_sync_merged_parent_test.go
- internal/actions/sync_branch.go
> fix: Address the case where the middle branch is merged to parent

- e2e_tests/stack_sync_delete_parent_test.go
- internal/actions/sync_branch.go
> fix: Update the parent HEAD even if rebasing is not needed

- cmd/av/helpers.go
- cmd/av/stack_sync.go
- internal/actions/pr.go
- internal/git/git.go
- internal/meta/jsonfiledb/db.go
- internal/utils/sanitize/filename.go
- internal/utils/sanitize/filename_test.go
Saves the pull request description (entered via editor) to a temporary file if creating the pull request fails. It will re-use the title/description if the user tries to re-create the PR (also just logs the file path to the console in case they want that).
The most common cause of this error (in my experience) is expired auth tokens and/or the base branch of a stack having been deleted on GitHub. (we should provide a better experience for the latter but that's outside the scope of this PR)
> feat: Save PR message if creation fails

- internal/meta/refmeta/import.go
> fix: Import into new db format should succeed if repo not previously initalized

- cmd/av/stack_tidy.go
> fix: Rebuild the children after deletions

- internal/actions/sync_branch.go
> fix: Handle the original parent is a trunk case

- cmd/av/stack_sync.go
- internal/actions/pr.go
- internal/actions/sync_branch.go
The rebase status is not that relevant to the callers; it only needs the
continuation. Branch is also not needed as it can be obtained from tx.
> refactor: Return a continuation directly

- cmd/av/stack_branchcommit.go
- e2e_tests/stack_branchcommit_test.go
- internal/git/diff.go
Fixes #129.
Technically (but not practically) breaking: `--all` is now equivalent to `av stack branch-commit -A` (before it was equivalent to `-a`).
> feat(stack branch-commit): Differentiate -a/-A flags

- e2e_tests/stack_sync_adopt_test.go
- internal/actions/reparent.go
> [MER-2352] Make branch adoption work

- cmd/av/stack_sync.go
- e2e_tests/stack_sync_all_test.go
- internal/actions/sync_stack.go
> [MER-2351] Add --all option to sync all branches

- cmd/av/stack.go
- cmd/av/stack_reorder.go
- go.mod
- go.sum
- internal/actions/reorder.go
- internal/reorder/cmds.go
- internal/reorder/errors.go
- internal/reorder/parse.go
- internal/reorder/parse_test.go
- internal/reorder/pick.go
- internal/reorder/pick_test.go
- internal/reorder/reorder.go
- internal/reorder/stackbranch.go
- internal/reorder/stackbranch_test.go
Breaking this into a few parts.
This PR is intended to just define the base scaffolding. Namely, we're just defining the structure of the `stack-branch` and `pick` commands (ultimately the goal is to support all the commands from `git rebase --interactive` in addition to some av specific ones like `stack-branch`).
This code is not called from anywhere currently.
> feat(stack reorder): Add command scaffolding

- cmd/av/stack_reorder.go
- internal/git/cherrypick.go
- internal/git/cherrypick_test.go
- internal/git/gittest/commit.go
- internal/git/internal.go
- internal/reorder/cmds.go
- internal/reorder/errors.go
- internal/reorder/pick.go
- internal/reorder/pick_test.go
- internal/utils/errutils/as.go
Implements the actual `pick` command (along with adding the necessary other things like `Repo.CherryPick`).
> feat(stack reorder): Implement PickCmd

- cmd/av/stack_branch.go
- internal/meta/jsonfiledb/readtx.go
- internal/reorder/cmds.go
- internal/reorder/cmds_test.go
- internal/reorder/pick.go
- internal/reorder/pick_test.go
- internal/reorder/reorder.go
- internal/reorder/reorder_test.go
- internal/reorder/stackbranch.go
> feat(stack reorder): Implement internal Reorder API

- cmd/av/stack_tidy.go
- docs/av-stack-tidy.1.md
> docs: Add manpage for `av stack tidy`

- cmd/av/stack_submit.go
- docs/av-stack-submit.md
> docs: Add manpage for `av stack submit`

- cmd/av/stack_diff.go
- cmd/av/stack_tree.go
- internal/actions/reparent.go
- internal/git/diff.go
This was originally gonna just be running the diff in interactive mode to enable the pager but I figured out the way were computing the diff wasn't quite right. I describe the complexities in comments in `stack_diff.go`.
I have branches like
```
* 2023-06-05-one-b 2d1f535  (2023-06-05-one)
|   
| * 2023-06-05-two-b 001f28f  (HEAD -> 2023-06-05-two)
|/  
| 
* 2023-06-05-one-a aba0167 
```
Before this change, running `av stack diff` on the second branch includes removing the changes from the second commit of branch one.
```diff
$ av stack diff
diff --git a/2023-06-05 b/2023-06-05
index aee8822..6dc6612 100644
--- a/2023-06-05
+++ b/2023-06-05
@@ -1,2 +1,2 @@
Mon Jun  5 15:02:42 PDT 2023
-Mon Jun  5 15:05:50 PDT 2023
+Mon Jun  5 15:05:04 PDT 2023
```
After this change, it shows just the diff …
> fix(stack diff): Compute stack diff correctly

- internal/actions/reparent.go
This log looks like "Adopting a branch master to Avmaster". Make it
"Adopting a branch master to Av".
> [MER-2417] Remove the unnecessary branch name in logging

- internal/actions/pr.go
- misc/vim/ftdetect/av-markdown.vim
- misc/vim/ftplugin/av-markdown.vim
- misc/vim/syntax/av-markdown.vim
This is a nice to have and a harmless change. The temp file created for
the pull-request title and body now has an extension '.av.md'. This is
anyway recognized as a markdown file for most of the editors, but this
extra 'av' extension allows us to have a special file type that supports
'%%' as a comment.
As an example, added a Vim plugin that recognize this file type and
treats '%%' as a comment.
> [MER-2418] Make it easy to detect a PR markdown

- docs/av-stack-diff.1.md
> docs: Add manpage for `av stack diff`

- cmd/av/stack_reorder.go
- internal/editor/editor.go
- internal/editor/editor_test.go
- internal/meta/branch.go
- internal/reorder/editor.go
- internal/reorder/reorder.go
- internal/reorder/stackbranch.go
- internal/utils/typeutils/is.go
> refac: add pr.go

- cmd/av/pr.go
- docs/av-auth-status.1.md
- docs/av-commit-amend.1.md
- docs/av-commit-create.1.md
- docs/av-commit-split.1.md
- docs/av-fetch.1.md
- docs/av-init.1.md
- docs/av-pr-create.1.md
- docs/av-stack-branch-commit.1.md
- docs/av-stack-branch.1.md
- docs/av-stack-diff.1.md
- docs/av-stack-next.1.md
- docs/av-stack-prev.1.md
- docs/av-stack-submit.1.md
- docs/av-stack-sync.1.md
- docs/av-stack-tidy.1.md
- docs/av-stack-tree.1.md
- docs/av.1.md
- docs/convert-manpages.go
- docs/internal/md2man/md2man.go
- docs/internal/md2man/roff.go
- go.mod
- go.sum
We are trying to use `docs/*` as both command manuals on the web as well
as online manual distributed along with the binary. For that, we want to
customize go-md2man output, especially the header part.
This includes a fork of https://github.com/cpuguy83/go-md2man. This
includes the title part and some whitespace handling
modifications.
Note that go-md2man is licensed under MIT license, which is the same as
this repository. The file independently have a license header and a
copyright notice with a SPDX header.
> [MER-2446] Adjust styles for web and manpages

- .goreleaser.yaml
- .pre-commit-config.yaml
https://goreleaser.com/deprecations/#archivesreplacements
archives.replacements is removed as of 2023-06-06.
> [MER-2449] Replace the deprecated "replacements"

- .gitignore
- .goreleaser.yaml
With this change, the archives have online manuals and they are
installed with Homebrew. Tested locally with goreleaser and local
formula.
> [MER-2452] Bundle manpages

- cmd/av/pr.go
- cmd/av/stack_branch.go
- docs/av-stack-branch.1.md
> feat: add force flag to stack branch rename

- cmd/av/pr.go
- cmd/av/stack_reorder.go
- internal/git/git.go
- internal/reorder/deletebranch.go
- internal/reorder/deletebranch_test.go
- internal/reorder/editor.go
- internal/reorder/parse.go
- internal/reorder/parse_test.go
- internal/utils/sliceutils/contains.go
- internal/utils/sliceutils/subtract.go
Have a branch structure:
```
* 2023-06-08-two-b ce20b00  (HEAD -> 2023-06-08-two)
| 
* 2023-06-08-two-a 1f8f16b 
| 
* 2023-06-08-one-b 061ed6e  (2023-06-08-one)
| 
* 2023-06-08-one-a a4db90d 
| 
* 2023-05-30-one-a (#957) 87232f0  (origin/main, origin/HEAD, main)
```
Run `av stack reorder` and delete the `stack-branch 2023-06-08-two` line (effectively merging all commits into `2023-06-08-one`):
Choose `e` to edit the plan:
(looks like unfortunately we lose the comment information, but this can be fixed in a future change)
Save the same plan, choose `o` to orphan the branches:
Confirmed that `2023-06-08-two` still exists and hasn't had it's HEAD modified.
Reset to the state above, but this time choose `d` to delete the branches:
> feat(stack reorder): Delete branches removed from reorder plan

- cmd/av/pr.go
- cmd/av/pr_status.go
- internal/utils/timeutils/timeutils.go
> feat: add associated botpr info to av pr status

- cmd/av/stack_branch.go
- docs/av-stack-branch.1.md
- e2e_tests/stack_branch_test.go
- internal/git/git.go
When a user renames a branch with git, this allows them to retroactively
fit the Av metadata as well.
> [MER-1962] Support retroactively rename the branches

- cmd/av/pr_create.go
> Fix: remove second create.

- internal/actions/sync_stack.go
Currently the branch deletion messages are concatenated to the previous
sync operation output. Separate the messages.
This also shows the message when no branch is deleted.
> [MER-2485] Separate the branch deletion messages

- cmd/av/stack_reorder.go
> [MER-2335] Remove the dev version check for reorder

- cmd/av/auth_status.go
- cmd/av/pr_queue.go
- cmd/av/pr_status.go
- internal/avgql/client.go
- internal/config/config.go
Feature request from a customer to support on-prem installations.
Ideally this would be configurable per-repo as it's possible that a user might have some repositories that use the \~\~cloud~~ version of Aviator and some that use on-prem, but that's not very likely at this point and I didn't want to add that complexity to this pull request.
> feat: Allow specifying Aviator API URL from configuration

- cmd/av/pr_queue.go
- docs/av-pr-queue.1.md
> [MER-2598] doc: Add `av pr queue` man page; hide unimplemented flags.

- cmd/av/pr_queue.go
- internal/actions/push.go
- internal/actions/sync_branch.go
Fixes a bug where branches other than the current branch in the stack would not be pushed during `av stack sync`.
The bug was essentially that `actions.Push` assumed that the branch to be pushed was the current branch and the calling code didn't match that assumption. I changed the `Push` function to take the branch name explicitly since 1) it doesn't actually require the branch to be checked out and 2) APIs with fewer non-obvious assumptions are generally better and less prone to this kind of bug.
> fix: Push correctly during av stack sync

- cmd/av/commit_amend.go
- cmd/av/commit_create.go
- cmd/av/fetch.go
- cmd/av/init.go
- cmd/av/main.go
- cmd/av/pr_create.go
- cmd/av/stack_submit.go
- cmd/av/stack_sync.go
> [MER-2188] Use gh auth token if it's available

- cmd/av/pr_create.go
- internal/actions/pr.go
- internal/config/config.go
This creates a PR in a draft state when the title contains "WIP". Can be
turned off in the config.
> [MER-2814] Automatically make a PR draft

- cmd/av/stack_reorder.go
> fix: Dont hide `av stack reorder` command

- cmd/av/stack_tree.go
- e2e_tests/stack_tree_test.go
- internal/git/diff.go
- internal/git/diff_test.go
> fix: Repo.Diff shouldn't fail given ambiguous branch names

- cmd/av/auth_status.go
- cmd/av/pr_status.go
- internal/avgql/viewer.go
This was previously resulting in `av pr status` showing junk if the user was not logged in.
> fix: Check authentication status in `av pr status`

- cmd/av/helpers.go
- internal/git/git.go
- internal/git/gittest/repo.go
> [MER-2744] fix: look for correct git dir path.

- cmd/av/helpers.go
- internal/actions/pr.go
- internal/editor/editor.go
- internal/git/git.go
- internal/git/gittest/repo.go
This has bit me a few times when flailing with vim. The file is saved successfully but Vim exits with a non-zero exit code and I've managed to lose big walls of text this way.
Going to test by causing vim to fail when creating this very PR.
It works!
```
Creating pull request for branch travis/mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero:
- pushing to origin/travis/mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero
- saved pull request description to /Users/travis/Aviator/av/.git/av/tmp/av-pr-travis-mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero.md (it will be automatically re-used if you try again)
error: text editor failed: command "vi" failed: exit status 2
```
> fix: Don't erase PR message if editor exits with a non-zero code

- .github/workflows/release.yml
- .goreleaser.yaml
Noticed some deprecation warnings while releasing (https://github.com/aviator-co/av/actions/runs/6578366058/job/17871949957). This fixes those.
> chore: fix goreleaser deprecations

- internal/actions/pr.go
Fixes a bug where running `av pr create` or `av stack submit` won't edit the base branch of a pull request that already exists.
I noticed this when I reparented a branch that I'd already created a PR for and noticed it didn't set the base branch correctly on GitHub.
> fix: Update base branch correctly in av pr create

- internal/actions/sync_branch.go
- internal/git/git.go
- internal/reorder/editor.go
- internal/reorder/plan.go
- internal/reorder/stackbranch.go
This was originally going to be just fixing an issue that occurs where running `av stack reorder` on a stack that has a branch with no commits.
That ended up being comparatively easy to fix (it's essentially just the two line change in `git.go`), but realized that we didn't actually include any instructions when running `av stack reorder`, so I added that.
Now, when editing a reorder plan, it looks like:
```
stack-branch 2023-10-20-blegg-1 --trunk main@49331c9878615a5227fe56ede8521f7e5d8462e7  # this branch has no commits
#
```
> feat: improve av stack reorder UX

- internal/actions/pr.go
> fix: Use upper/lowercase to find pull request template

- cmd/av/stack.go
- cmd/av/stack_branch.go
- cmd/av/stack_branchcommit.go
- cmd/av/stack_foreach.go
- cmd/av/stack_next.go
- cmd/av/stack_prev.go
- cmd/av/stack_tree.go
- e2e_tests/stack_foreach_test.go
- internal/utils/executils/executils.go
Adds a way to execute a custom command on each branch in the stack.
Fixes #210.
```
GIT_PAGER='' av stack for-each -- git show --format='subject: %s' --quiet HEAD -- 
Executing command git show "--format=subject: %s" --quiet HEAD -- for 3 branches:
- switching to branch 2023-11-13-one
subject: 2023-11-13-one-a
- switching to branch 2023-11-13-two
subject: 2023-11-13-two-a
- switching to branch 2023-11-13-three
subject: 2023-11-13-three-a
```
> feat: Implement `av stack for-each` command

- dev/tag-release
> chore: Add tag-release script

- internal/config/config.go
- internal/gh/client.go
Fixes #215.
We're taking the base URL from the global config object which might not be suuuuper ideal but this is all internal code anyway.
Unfortunately, I don't have a way to test against a GHES instance but this *should* work.
> [MER-3206] Fix github.baseURL configuration

- cmd/av/auth_status.go
- cmd/av/main.go
- internal/avgql/viewer.go
- internal/gh/error.go
- internal/gh/viewer.go
> fix: Make av auth status output less confusing

- internal/actions/pr.go
Add `root` and `data/` as default PR template paths, in addition to `.github/`. These are common paths mentioned in the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template) for creating PR templates.
Created a test repro with `pull_request_template.md` in the root and verified that it's picked up when calling `av pr create`
```
❯ go run ./cmd/av -C /Users/andrew/dev/projects/test pr create
```
```
%% Creating pull request for branch 'foo'
%% Lines starting with '%%' will be ignored and an empty message aborts the
%% creation of the pull request.
%% Pull request title (single line)
Hello world
%% Pull request body (multiple lines)
A test PR template
%% …
```
> Add root and data/ as PR template paths

- internal/actions/sync_branch.go
- internal/git/log.go
- internal/git/log_test.go
When a PR gets closed by "Close #123", usually GitHub marks the PR to be
closed by certain commit. However, this mechanism is not reliable, and
sometimes GitHub doesn't mark it so and just close it. This breaks the
merge commit detection since av-cli doesn't have a way to know it from
GitHub API.
By using git-log, we can figure out whether there's actually a commit
that closes the PRs with this comment. This adds that extra detection
method.
In order to make this work, it moves the timing of git-fetch. This is
needed in order for a local repository to have commits in the upstream
to check the commit messages.
> [MER-3309] Add an extra merge commit detection based on commit messages

- cmd/av/stack_sync.go
- cmd/av/stack_tidy.go
- internal/actions/tidy.go
I think this should happen automatically on av stack sync. Otherwise, av
stack sync will result in an error that it cannot find a branch in the
repository.
> [MER-3360] Run av stack tidy on av stack sync

- cmd/av/stack_branchcommit.go
- internal/config/config.go
Resolves #227 
To add a branch name prefix, set the following config:
```
pullRequest:
branchNamePrefix: "av/"
```
> Introducing BranchNamePrefix

- internal/actions/pr.go
HEAD points to the currently checked out ref. Use the right branch name.
> [MER-3757] Use the proper branch name for getting a list of commits

- internal/reorder/plan.go
The local `master` might be behind the remote `master` branch. Because
of this, many unrelated commits are shown in `av stack reorder`. Use the
remote tracking branch (assuming it exists) to calculate the merge base.
Fixes #249
> Calculate the merge base based on the remote tracking branch

- cmd/av/main.go
- internal/config/config.go
Previously, it finds a config in some config dirs or in
`.git/config.$EXT`. This changes the config loading code to do the
followings:
* Change the repository config path from `$GIT_DIR/config.yaml` to
`$GIT_COMMON_DIR/av/config.yaml`. `$GIT_COMMON_DIR` is always (e.g.
`.git` dir). `$GIT_DIR` can point to something else under certain
situations.
* Loads both global configs (`~/.config/av/config.yaml`) and repository
config (`.git/av/config.yaml`). The repository config overrides the
global config.
> Support per-repo config properly

- cmd/av/commit_amend.go
- cmd/av/commit_create.go
- e2e_tests/commit_amend_test.go
- e2e_tests/commit_create_test.go
- e2e_tests/helpers.go
- internal/actions/sync_stack.go
- internal/git/gittest/commit.go
- internal/git/gittest/files.go
Currently, `av commit create` and `av commit amend` will sync dependent branches. This also ends up fetching and pushing to the remote in the process, which isn't expected as the remote gets out of sync as the head branch remains unpushed. Syncing with the remote repo ought to happen separately with `av stack sync`.
Also added some end to end tests for these commands.
Closes #263.
> Don't fetch/push upstack branches on av commit create/amend

- cmd/av/stack_tree.go
- internal/utils/stackutils/stackutils.go
No functional changes. Move `buildTree()` and other helper functions to a new `stackutils` module, and export `BuildStackTree()` from there. We'll later reuse `buildStackTree()` there to construct the tree of nodes needed for the stack to be written to PR bodies.
See #264 for context.
> Move stack helpers to separate module for reuse

- internal/actions/pr.go
- internal/actions/pr_test.go
As part of adding support for including the stack in PR bodies (see #264), we'll need to extend templating support to handle more than one section:
```
{ stack here } 
Here is the main PR body description.
```
The current `ParsePRMetadata()` implementation is efficient, but makes it hard to support another section.
This PR updates `ParsePRMetadata` and `AddPRMetadata` to instead make use of substrings and `strings.Builder`. Performance isn't really a concern here - these PR bodies aren't that big and we spend a lot more time interacting with the `git` CLI anyway.
> Refactor PR body parsing

- cmd/av/stack_foreach.go
- cmd/av/stack_submit.go
- cmd/av/stack_sync.go
- e2e_tests/stack_sync_test.go
- internal/meta/branch.go
When running `av stack sync`, sync the entire "stack" (starting from root) instead of just the subtree from the current branch.
Updated test to document new behavior.
> Process entire stack subtree when syncing stack

- cmd/av/stack_branch.go
address #244
```sh
$ av stack branch new-branch parent-branch
```
> Support `av stack branch  <new branch> <base branch>`

- cmd/av/pr_create.go
- cmd/av/stack_submit.go
- internal/actions/pr.go
- internal/actions/pr_test.go
- internal/actions/sync_branch.go
- internal/config/config.go
- internal/meta/branch.go
- internal/utils/stackutils/stackutils.go
This PR adds a new configuration option, `pullRequest.writeStack`, that if enabled will add stack trees directly to GitHub pull requests.
For ease of navigation, these are added to the top as follows:
And when expanded, show the stack of requests from the latest PR down to the trunk branch:
Most PR stacks tend to be linear, but an alternate format is used if there are forks in the stack that make it look more like a tree:
This isn't the default format since I personally think the one above is cleaner to read, especially on phones that run out of horizontal real estate.
> Enable writing stack trees to PR bodies

- cmd/av/stack_submit.go
- internal/actions/pr.go
When run with a stack of unpushed branches, `av stack submit` ends up opening a bunch of new browser windows for each PR one by one, which is a bit disruptive. ~Since we're pushing a single stack, only open the last-created PR once completed.~ Open all the PRs at the end once created instead.
> Update av stack submit to open PRs in browser after entire stack is submitted

- internal/git/rebase.go
With
https://github.com/git/git/commit/244001aa20d7a6411d8c920f34799df484d9a787,
the error message has been changed. Follow up with this change.
> Check the git error message in a case-insensitive way

- cmd/av/pr_create.go
- cmd/av/stack_submit.go
- cmd/av/stack_tree.go
- internal/actions/pr.go
- internal/actions/pr_test.go
- internal/actions/sync_branch.go
- internal/utils/stackutils/stackutils.go
Additional data can be obtained on the caller side.
> Make stackutils return only tree structure

- cmd/av/commit_amend.go
- cmd/av/commit_create.go
- cmd/av/stack_reorder.go
- cmd/av/stack_sync.go
- internal/actions/sync_stack.go
- internal/git/state_file.go
- internal/reorder/reorder.go
- internal/reorder/reorder_test.go
> Make a generic state file read/write mechanism

- .goreleaser.yaml
Tested `deb` with local debian VM. Tested `PKGBUILD` with local Arch Linux. RPM not tested.
> Add deb, rpm and AUR configs to goreleaser

- e2e_tests/av.go
- e2e_tests/commit_amend_test.go
- e2e_tests/commit_create_test.go
- e2e_tests/stack_branch_test.go
- e2e_tests/stack_branchcommit_test.go
- e2e_tests/stack_orphan_test.go
- e2e_tests/stack_reparent_test.go
- e2e_tests/stack_sync_adopt_test.go
- e2e_tests/stack_sync_all_test.go
- e2e_tests/stack_sync_amend_test.go
- e2e_tests/stack_sync_delete_merged_test.go
- e2e_tests/stack_sync_delete_parent_test.go
- e2e_tests/stack_sync_merge_commit_test.go
- e2e_tests/stack_sync_merged_parent_test.go
- e2e_tests/stack_sync_test.go
- e2e_tests/stack_sync_trunk_test.go
There are some variations on the test utilities. This change unifies
them.
> Use the same test utilities

- cmd/av/stack_switch.go
- cmd/av/stack_tree.go
- internal/actions/pr.go
- internal/actions/sync_branch.go
- internal/utils/stackutils/stackutils.go
We want to use this outside of PR context.
> Rename the stackutils methods

- cmd/av/stack_switch.go
- internal/git/git.go
- internal/sequencer/planner/planner.go
- internal/sequencer/planner/targets.go
- internal/sequencer/sequencer.go
This is similar to git's sequencer, but it's for re-stacking branches.
https://github.com/git/git/blob/master/sequencer.h
This object is responsible for re-stacking branches based on the planned
operations.
> Add new sequencer object

- e2e_tests/mock_ghgql_server.go
- e2e_tests/stack_reparent_test.go
- e2e_tests/stack_sync_adopt_test.go
- e2e_tests/stack_sync_all_test.go
- e2e_tests/stack_sync_amend_test.go
- e2e_tests/stack_sync_delete_merged_test.go
- e2e_tests/stack_sync_delete_parent_test.go
- e2e_tests/stack_sync_merge_commit_test.go
- e2e_tests/stack_sync_merged_parent_test.go
- e2e_tests/stack_sync_test.go
- e2e_tests/stack_sync_trunk_test.go
- internal/gh/pullrequest.go
- internal/git/gittest/repo.go
This allows us to test stack sync with the default option.
> Run mock GitHub server for testing

- cmd/av/commit_amend.go
- cmd/av/commit_common.go
- cmd/av/commit_create.go
- cmd/av/helpers.go
- cmd/av/stack_adopt.go
- cmd/av/stack_branch.go
- cmd/av/stack_reparent.go
- cmd/av/stack_restack.go
- cmd/av/stack_sync.go
- docs/av-stack-reparent.1.md
- docs/av-stack-restack.1.md
- e2e_tests/stack_reparent_test.go
- e2e_tests/stack_restack_test.go
- internal/git/state_file.go
- internal/meta/branch.go
- internal/sequencer/planner/planner.go
- internal/sequencer/sequencerui/ui.go
- internal/utils/stackutils/stackutils.go
This extracts the UI component for restacking and uses it in av stack
restack, av stack reparent, av commit amend, and av commit create.
> Use the same code as av stack restack in other commands

- cmd/av/stack_next.go
- go.mod
- go.sum
A stack next command that supports interactively selecting the path you want to navigate through. 
For example if you have multiple stacks on top of your trunk (like below) and you run `av stack next`
It will now prompt you to ask which one you want to use:
This is a proposal and uses the github.com/erikgeiser/promptkit library, if this is accepted and you have a preferred prompt library let me know.
> Add interactive `stack next`

- cmd/av/stack_prev.go
When no args are provided and you are at the bottom of the stack `stack prev` moves to the trunk
> feat: allow `stack prev` to move to the trunk of the stack

- cmd/av/stack_next.go
- cmd/av/stack_reparent.go
- cmd/av/stack_restack.go
- cmd/av/stack_sync.go
- cmd/av/stack_tree.go
- internal/sequencer/sequencerui/ui.go
- internal/utils/stackutils/render_tree.go
> Unify the styles of the command output

- cmd/av/stack_reparent.go
> Check reparent arguments before running the command

- cmd/av/stack_sync.go
- e2e_tests/stack_sync_all_test.go
- e2e_tests/stack_sync_delete_merged_test.go
- e2e_tests/stack_sync_trunk_test.go
> Exit when a deprecated flag is specified

- .github/workflows/release.yml
- .goreleaser.yaml
Also update the goreleaser configuration to use the latest version of
the config schema.
> Update the release workflow to use the GITHUB_TOKEN and SSH key

- .goreleaser.yaml
> Fix SSH URL

- internal/treedetector/detector.go
Without this, if the trunk branch points to a merge commit, av stack
adopt won't work.
> Fix av stack adopt to detect the trunk branch first

- internal/gh/ghui/push.go
https://linear.app/mergequeue/issue/MER-4307/swap-the-order-of-push-pr-update-to-avoid-the-unintended-ci-triggers
> Update the PR metadata before pushing to the remote

- cmd/av/main.go
- cmd/av/render_error.go
- cmd/av/stack_branch.go
- cmd/av/stack_switch.go
- e2e_tests/stack_orphan_test.go
- e2e_tests/stack_restack_test.go
- e2e_tests/stack_sync_amend_test.go
- e2e_tests/stack_sync_delete_merged_test.go
- e2e_tests/stack_sync_delete_parent_test.go
- e2e_tests/stack_sync_merge_commit_test.go
- e2e_tests/stack_sync_merged_parent_test.go
- e2e_tests/stack_sync_test.go
- e2e_tests/stack_sync_trunk_test.go
Previously the help line was on the same line as master.
> Fix the position of the help message in the stack switch view

- internal/actions/pr.go
to detect reason and explain it for #305
(Does this change work as you intended?)
> Check a parent branch merge commit exists or not

- internal/git/git.go
- internal/git/gitui/prune.go
`git checkout` can create a new branch. Intention here is to switch to
something that is not a branch, so we use `git switch --detach` instead.
Fixes #357.
> Use detached HEAD when pruning branches

- internal/git/gitui/prune.go
This is a continuation of #357. There are people who prefers checkout
the default branch if the current branch is deleted after av stack sync.
All things considered, change the behavior like this. After av stack
sync:
1. If the originally checked out branch still exists, check it out.
2. If the originally checked out branch is deleted, check out the
default branch if it exists.
3. If the default branch doesn't exist, check out the remote tracking
branch of the default branch if it exists. (It should exist at this
point usually.)
4. Otherwise, do nothing.
This should satisfy all the parties.
> Try checkout the default branch if the current branch is deleted

- cmd/av/stack_adopt.go
- internal/git/git.go
- internal/treedetector/detector.go
As described in https://github.com/aviator-co/av/issues/364, it's
possible that Git has a more efficient way to calculate the merge bases.
> Use git-merge-base for the fast merge-base detection

- cmd/av/stack_sync.go
- docs/av-stack-sync.1.md
- internal/sequencer/planner/planner.go
See https://github.com/aviator-co/av/issues/348#issuecomment-2243950078
> Conditionally sync the branches

- internal/utils/colors/bgcolor.go
> Add a workaround for the rendering stuck issue

- cmd/av/helpers.go
- cmd/av/stack_adopt.go
- cmd/av/stack_reparent.go
Fixes https://github.com/aviator-co/av/issues/406
> Strip the remote name from the specified parent

- e2e_tests/stack_restack_test.go
- e2e_tests/stack_sync_test.go
- internal/actions/pr.go
- internal/git/git.go
- internal/git/gittest/repo.go
Fixed with https://github.com/codespell-project/codespell
> Fix spelling errors

- cmd/av/stack_adopt.go
Fixes https://github.com/aviator-co/av/issues/414
> Explain single branch adoption use case in av stack adopt help

- cmd/av/stack_next.go
- internal/actions/tidy.go
When the parent branch is deleted from the DB, it can go infinite loop.
> Fix the infinite loop in av stack tidy

- .goreleaser.yaml
Make it slightly simpler for people who use homebrew to get autocompletions for the cli
> Automate completions for homebrew installs

- cmd/av/stack_branch.go
We suppress cobra usage output across the board, but in the 0 arg case for stack branch we should show the user the usage rather than a generic "error: accepts between 1 and 2 arg(s), received 0"
> Make 0 arg state for stack branch more user friendly

- cmd/av/commit_amend.go
Adds the --flag to `av commit amend` to match `av commit create`
> feat: add --all flag to av commit amend

- .goreleaser.yaml
- README.md
> Fix template naming and update README

- internal/gh/ghui/push.go
Before I used `getPRs` method ref: (https://github.com/aviator-co/av/blob/master/internal/gh/ghui/push.go#L323)
However, the method only returns push candidates branches ref: (https://github.com/aviator-co/av/blob/master/internal/gh/ghui/push.go#L325). In my understanding correct, when target branch is a push candidate branch, this logic will work well. But if the target branch is **not** a push candidate branch, it won't work well.
So, I updated to check PR directly.
> Issue #440

- cmd/av/main.go
- cmd/av/restack.go
- cmd/av/stack.go
- cmd/av/sync.go
- demos/stack_restack/stack_restack.tape
- docs/av-commit.1.md
- docs/av-restack.1.md
- e2e_tests/restack_test.go
- internal/sequencer/sequencerui/ui.go
> Move av stack restack to av restack 

- cmd/av/helpers.go
- cmd/av/restack.go
- cmd/av/switch.go
> Add autocomplete for 'av switch'

- cmd/av/adopt.go
- cmd/av/branch.go
- cmd/av/commit.go
- cmd/av/helpers.go
- cmd/av/reparent.go
- cmd/av/stack_branchcommit.go
- docs/av-commit.1.md
> Add support for '--parent' on 'av commit -b'

- cmd/av/tidy.go
- internal/actions/tidy.go
> fix #486, 'av tidy' not respecting branches not off trunk

- cmd/av/pr.go
> Wrong deprecation warning on 'av pr create'

- cmd/av/branch.go
- docs/av-branch.1.md
> add av branch --split to manpages

- cmd/av/branch.go
Somehow git checkout is failing in the branch split. We anyway do not
need to checkout because there is no change in the worktree. We just
need to update the HEAD symref.
> Use ref update and avoid doing git checkout

- cmd/av/branch.go
When creating a new branch from a trunk branch, it should branch from
the parent remote tracking branch. This hasn't been an issue if the
trunk branch is the default branch (such as main / master), but if this
is used with a additionalTrunkBranches, it branches off from main /
master always rather than the specified additional trunk branch.
> Branch off from the parent branch

- cmd/av/adopt.go
> Show an error message when there is no branch to adopt

- docs/internal/md2man/roff.go
- internal/git/git.go
This is a follow up to https://github.com/aviator-co/av/pull/541. This
is used to indicate that the git command is being invoked by av-cli.
The git hooks can use this information to behave differently.
> Set IN_AV_CLI environment variable to 1 when invoking git commands

- internal/actions/pr.go
- internal/git/revlist.go
- internal/reorder/stackbranch.go
Fixes #423
Also fixes a case where `av` fails when there's a branch with the same name as a
file.
> Do not make --parent or --trunk obligatory

- cmd/av/pr.go
- cmd/av/sync.go
Interactive for better user experience (show progress of the hook as it is running) and exit on error so that checks that fail actually stop the command.
> Make pre-av hooks interactive and exit on error.

- cmd/av/pr.go
- cmd/av/sync.go
> Address the nil dereference

- cmd/av/main.go
> failure to fetch latest release version should be debug only message

- .pre-commit-config.yaml
- cmd/av/reparent.go
> Switch autocomplete for reparent to using valid branch names

- .goreleaser.yaml
> add homebrew fish autocompletions

- cmd/av/squash.go
Realised when testing this that the CLI was squashing all the commits of a branch into the last commit of the parent. This was different to the behaviour of other stacked CLI tooling and not what I initially intended
> fix av squash command

- cmd/av/squash.go
- e2e_tests/squash_test.go
The previous fix #575  attempted to fix the squash command, but actually was incorrect and I believe the original command was working as expected all along. I suspect the issue I was seeing was actually down to my repo being in a bad state - _still investigating the cause there_
To try and prevent this happening again I have added a bunch of tests (with the help from opencode), to try ensure that the behaviour remains as expected
> revert Fix av squash pr, and add comprehensive tests

- cmd/av/commit_common.go
- cmd/av/reparent.go
- cmd/av/restack.go
- cmd/av/sync.go
- internal/actions/pr.go
- internal/gh/ghui/push.go
- internal/git/git.go
- internal/git/gitui/prune.go
- internal/sequencer/sequencerui/ui.go
- internal/treedetector/detector.go
- internal/utils/uiutils/err_cmd.go
When editing an existing PR with `av pr --edit`, we fetch the existing
PR body from GitHub and launch an editor to edit it. However, the PR
body on GitHub might already has a PR metadata section / PR stack info
appended to it, which we don't want to show in the editor. Strip them
from the body.
> Strip the PR metadata from the PR body

- cmd/av/adopt.go
- cmd/av/helpers.go
- cmd/av/main.go
- cmd/av/next.go
- cmd/av/pr.go
- cmd/av/pr_status.go
- cmd/av/sync.go
- docs/internal/md2man/roff.go
- e2e_tests/mock_ghgql_server.go
- internal/gh/ghui/push.go
- internal/gh/pullrequest.go
- internal/gh/repository.go
- internal/git/git.go
- internal/git/gittest/repo.go
- internal/git/gitui/prune.go
- internal/git/show.go
- internal/git/status.go
- internal/meta/branch.go
- internal/reorder/editor.go
- internal/sequencer/planner/planner.go
- internal/utils/logutils/logutils.go
- internal/utils/maputils/copy.go
- internal/utils/sliceutils/contains.go
- internal/utils/stackutils/stackutils.go
- internal/utils/templateutils/templateutils.go
- internal/utils/uiutils/add_newline.go
- internal/utils/uiutils/prompt.go
- internal/utils/uiutils/simple_message.go
This is to extract / reuse UI components as tea.Model, so that they can
be composed in other tea.Models. No substantial behavior changes. The
"sync all" prompt is now persisted after the user answers it, ctrl+c now
works at any timing.
> Abstract parts as tea.Model where possible in av sync
